# Generated by Django 5.2.4 on 2025-07-28 07:22

import cloudinary.models
import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
