# Generated by Django 5.2.4 on 2025-08-16 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0002_alter_memorial_country_alter_memorial_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='memorial',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memorials', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
