# Generated by Django 5.2.4 on 2025-08-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0003_alter_memorial_options_memorial_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('aunt_uncle', 'Aunt/Uncle'), ('niece_nephew', 'Niece/Nephew'), ('cousin', 'Cousin')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships_from', to='memorials.memorial')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships_to', to='memorials.memorial')),
            ],
            options={
                'unique_together': {('person_a', 'person_b', 'relationship_type')},
            },
        ),
    ]
