# Generated by Django 5.2.4 on 2025-09-21 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0004_familyrelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memorial',
            index=models.Index(fields=['approved'], name='memorials_m_approve_c5e12d_idx'),
        ),
        migrations.AddIndex(
            model_name='memorial',
            index=models.Index(fields=['created_at'], name='memorials_m_created_7fd8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='memorial',
            index=models.Index(fields=['full_name'], name='memorials_m_full_na_cc187d_idx'),
        ),
        migrations.AddIndex(
            model_name='memorial',
            index=models.Index(fields=['country'], name='memorials_m_country_7ae458_idx'),
        ),
        migrations.AddIndex(
            model_name='memorial',
            index=models.Index(fields=['approved', '-created_at'], name='memorials_m_approve_a0322f_idx'),
        ),
    ]
