# Generated by Django 5.2.4 on 2025-10-01 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0005_memorial_memorials_m_approve_c5e12d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='is_shareable',
            field=models.BooleanField(default=True, help_text='Allow this memorial to be shared publicly'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='share_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this memorial has been shared'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
