# Generated by Django 5.2.4 on 2025-10-15 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0005_memorial_memorials_m_approve_c5e12d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyrelationship',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='suggestion_note',
            field=models.TextField(blank=True, help_text='Optional explanation for this relationship'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='verification_status',
            field=models.CharField(choices=[('user_suggested', 'User Suggested'), ('creator_verified', 'Creator Verified'), ('auto_approved', 'Auto Approved')], default='user_suggested', max_length=20),
        ),
        migrations.AlterField(
            model_name='familyrelationship',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyrelationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
