# Generated by Django 5.2.4 on 2025-10-18 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0006_alter_familyrelationship_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('relationship_suggested', 'Relationship Suggested'), ('relationship_approved', 'Relationship Approved'), ('relationship_rejected', 'Relationship Rejected'), ('new_family_member', 'New Family Member')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_memorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorials.memorial')),
                ('related_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorials.familyrelationship')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='memorials_n_user_id_a27e66_idx'), models.Index(fields=['-created_at'], name='memorials_n_created_bf0d1b_idx')],
            },
        ),
    ]
