# Generated by Django 5.2.4 on 2025-10-18 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('relationship_suggested', 'Relationship Suggested'), ('relationship_approved', 'Relationship Approved'), ('relationship_rejected', 'Relationship Rejected'), ('new_family_member', 'New Family Member'), ('death_anniversary', 'Death Anniversary'), ('birthday_anniversary', 'Birthday Anniversary')], max_length=50),
        ),
        migrations.CreateModel(
            name='MemorialReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_settings_enabled', models.BooleanField(default=False)),
                ('notify_death_anniversary', models.BooleanField(default=True)),
                ('notify_birthday', models.BooleanField(default=True)),
                ('notify_creator_only', models.BooleanField(default=True)),
                ('notify_all_family', models.BooleanField(default=False)),
                ('custom_reminder_date', models.DateField(blank=True, null=True)),
                ('custom_reminder_label', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memorial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='memorials.memorial')),
                ('specific_users', models.ManyToManyField(blank=True, related_name='memorial_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('scheduled_date', models.DateField()),
                ('year_count', models.IntegerField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.memorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('enable_anniversary_notifications', models.BooleanField(default=True)),
                ('notify_death_anniversaries', models.BooleanField(default=True)),
                ('notify_birthdays', models.BooleanField(default=True)),
                ('notify_milestones', models.BooleanField(default=True)),
                ('notify_week_before', models.BooleanField(default=True)),
                ('notify_day_before', models.BooleanField(default=True)),
                ('notify_on_day', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
