# Generated by Django 5.2.4 on 2025-10-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0009_userprofile_created_at_userprofile_premium_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.IntegerField(default=0)),
                ('match_reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('my_memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_suggestions_for', to='memorials.memorial')),
                ('suggested_memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_suggestions_by', to='memorials.memorial')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['my_memorial', 'status'], name='memorials_s_my_memo_ddc0f2_idx'), models.Index(fields=['created_at'], name='memorials_s_created_7148dd_idx')],
                'unique_together': {('my_memorial', 'suggested_memorial')},
            },
        ),
    ]
