# Generated by Django 5.2.4 on 2025-10-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0011_premiumpackage_usersubscription_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorials.premiumpackage'),
        ),
    ]
