# Generated by Django 5.2.4 on 2025-10-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0012_alter_usersubscription_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorialPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Upload high-quality memorial photos', upload_to='memorial_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this photo', max_length=500, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Display this as the main memorial photo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in gallery (lower numbers first)')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='memorials.memorial')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_memorial_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memorial Photo',
                'verbose_name_plural': 'Memorial Photos',
                'ordering': ['order', '-uploaded_at'],
                'unique_together': {('memorial', 'is_primary')},
            },
        ),
        migrations.AddField(
            model_name='memorial',
            name='primary_photo',
            field=models.OneToOneField(blank=True, help_text='Primary photo displayed in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorial_primary', to='memorials.memorialphoto'),
        ),
    ]
