# Generated by Django 5.2.4 on 2025-10-28 05:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0013_memorialphoto_memorial_primary_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorialphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
