# Generated by Django 5.2.4 on 2025-10-28 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0014_alter_memorialphoto_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memorialphoto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='primary_photo',
        ),
        migrations.AddConstraint(
            model_name='memorialphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('memorial', 'is_primary'), name='unique_memorial_primary_photo'),
        ),
    ]
