"""
Django settings for memohera_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables safely
try:
    from dotenv import load_dotenv
    load_dotenv(dotenv_path=os.path.join(BASE_DIR, '.env'))
except ImportError:
    pass  # dotenv not available, skip loading .env file


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dn-)tyh$!ubjl&ph0y0#k4q^yshi&3^!i1-w)#hsmm2#&-^3z&'

if os.environ.get('RAILWAY_ENVIRONMENT'):
    print("=== RAILWAY ENVIRONMENT DETECTED ===")
    
    # Database
    DATABASE_URL = os.environ.get('DATABASE_URL')
    if DATABASE_URL:
        print(f"Database URL found: {DATABASE_URL[:30]}...")
        DATABASES = {
                    'default': {
                        'ENGINE': 'django.db.backends.sqlite3',
                        'NAME': '/tmp/db.sqlite3',  # Use /tmp for Railway's ephemeral storage
                    }
        }
    
    # Security settings
    SECRET_KEY = os.environ.get('SECRET_KEY', SECRET_KEY)
    DEBUG = True  # Keep True until we fix all issues
    ALLOWED_HOSTS = ['*']

    # Static files for production
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
   
    print("=== PRODUCTION MODE ACTIVATED ===")

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# For local development
DEBUG = True
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'memoheraj-production.up.railway.app',
    '.railway.app',  # This allows all Railway subdomains
]
# # Production overrides
# if os.environ.get('RAILWAY_ENVIRONMENT'):
#     ALLOWED_HOSTS = [
#         'web-production-43b9.up.railway.app',
#         '.railway.app',
#         '.up.railway.app',  # Add this too
#         'localhost',
#         '127.0.0.1'
#     ]
#     # SECURITY WARNING: don't run with debug turned on in production!
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# CSRF settings for production
CSRF_TRUSTED_ORIGINS = [
    'https://web-production-43b9.up.railway.app',
    'http://web-production-43b9.up.railway.app',  # Include both HTTP and HTTPS
]

# Also make sure these are set correctly
CSRF_COOKIE_SECURE = True  # Only if using HTTPS
CSRF_COOKIE_HTTPONLY = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'memorials',
    'cloudinary',
    'cloudinary_storage',    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add directly here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'memohera_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'memorials.context_processors.language_context',  # Add this line
            ],
        },
    },
]






WSGI_APPLICATION = 'memohera_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Cloudinary credentials
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
ENABLE_FAMILY_RELATIONSHIPS = True  # Easy on/off switch
AUTO_APPROVE_MEMORIALS = True

LANGUAGES = [
    ('en', _('English')),
    ('zh-cn', _('中文 (简体)')),    # Chinese Simplified - correct code
    ('es', _('Español')),          # Spanish
    ('ar', _('العربية')),           # Arabic
    ('fr', _('Français')),         # French
    ('de', _('Deutsch')),          # German
    ('pt', _('Português (Brasil)')),  # Portuguese - use 'pt' instead of 'pt_BR'
    ('ru', _('Русский')),          # Russian
    ('ja', _('日本語')),            # Japanese
    ('hi', _('हिन्दी')),            # Hindi
    ('el', _('Ελληνικά')),  # Greek
]

# Also update the flags mapping:
LANGUAGE_FLAGS = {
    'en': '🇺🇸',
    'zh-cn': '🇨🇳',   # Updated
    'es': '🇪🇸',
    'ar': '🇸🇦',
    'fr': '🇫🇷',
    'de': '🇩🇪',
    'pt': '🇧🇷',      # Updated
    'ru': '🇷🇺',
    'ja': '🇯🇵',
    'hi': '🇮🇳',
    'el': '🇬🇷',  # Greek flag
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'create_memorial'   # after login
LOGOUT_REDIRECT_URL = 'about'         # after logout


STATICFILES_DIRS = [
    BASE_DIR / "static",  # ← This points to memohera_j/static/
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add these to your settings.py




# Path where translation files will be stored
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # This should be after SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
